name: test

on: [push]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        st-version: [4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip pycodestyle pep257 mkdocs mkdocs-material
          curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
          chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel
        shell: bash
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
        with:
          coverage: true
          codecov-upload: true
      - name: Build mkdocs
        if: runner.os == 'Linux'
        run: mkdocs build --verbose --clean --strict;
      - name: Deploy to GitHub Pages
        if: runner.os == 'Linux' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: site
