#!/bin/sh

WALLPAPER_DIR="$HOME/.local/share/wallhaven"
USED_WALLPAPER_DIR="$HOME/.local/share/wallhaven_used"


# create folders if not exist.
[ -d "$WALLPAPER_DIR" ] || mkdir -p "$WALLPAPER_DIR"
[ -d "$USED_WALLPAPER_DIR" ] || mkdir -p "$USED_WALLPAPER_DIR"

# check if wallpaper dir is empty
[ -z "$(ls -A $WALLPAPER_DIR)" ] && mv $USED_WALLPAPER_DIR/* $WALLPAPER_DIR


if [ -z "$1" ]; then
	temp_wallpaper=$(find $WALLPAPER_DIR -type f | shuf -n 1)
	file_name=$(basename $temp_wallpaper)

	mv $temp_wallpaper $USED_WALLPAPER_DIR #move current wall to used wall folder 
	
	wallpaper="$USED_WALLPAPER_DIR/$file_name"

elif echo "$1" | grep -q "/"; then
	wallpaper="$1"
else
	wallpaper="$HOME/.local/share/wallhaven/$1"
fi

#set wallpaper
gsettings set org.gnome.desktop.background picture-uri-dark $wallpaper

#delete old cached themes
wal -c

#generate new theme
wal -i $wallpaper

# #generate telegram theme
# ~/.telegram-palette-gen/telegram-palette-gen --wal