#!/bin/bash

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set Default text from clipboard
default=$(xclip -o)

#Get query
query=$(echo "$default" | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -fn 'JetBrains Mono:size=14' -p "Search on Google : " -l 1 | tr ' ' '+' | head -n 1) 

#Search if query is not empty
[[ -z "$query" ]] || brave-browser "https://www.google.com/search?q=$query"

exit 0