#!/bin/bash

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

#Get query
query=$(: | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -fn 'JetBrains Mono:size=14' -p "Search Leetcode Problem : " | tr ' ' '+' | head -n 1) 

#Search if query is not empty
[[ -z "$query" ]] || brave-browser "https://leetcode.com/problemset/all/?search=$query"

exit 0