#!/bin/zsh

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

# video dir path
vid_dir="/mnt/ECHO/Videos/YT-Downloads"

# file or folder to play
eval mpv $(find $vid_dir | awk -F/ '{ if($6) {print "[" $6 "] :" $0}}' | dmenu -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -fn 'PatrickHand:size=13' -p "Watch : " -i -l 10 | cut -d':' -f2  | sed -E 's/([^a-zA-Z0-9_/])/\\\1/g' )
