#!/bin/bash

# File Path
input_file="$HOME/Downloads/youtube_links.txt"

#quality
quality="1080"

if [[ "$1" == "1080" || "$1" == "480" || "$1" == "720" || "$1" == "360" ]]; then
    quality="$1"
else
    quality="1080"
fi

# Trap the Ctrl+C signal and call the terminate function
terminate() {
    echo "Script terminated by user."
    exit 1
}
trap terminate SIGINT

# Read Yt links and download it in a folder
line_number=0
total_lines=$(wc -l < "$input_file")

while IFS= read -r line; do
    ((line_number++))
    clear
    echo "[Download] Downloading item $line_number of $total_lines"
    yt-dlp -f "bestvideo[height<=$quality]+ba" --add-chapters "$line" -o '~/Videos/YT-Downloads/Watch Later/%(title)s.%(ext)s'
done < "$input_file"

if [ $? -eq 0 ]; then
    notify-send "Download Complete" "The download has finished."
  else
    notify-send "Download Failed" "There was an error during the download."
fi

# Remove file
rm "$input_file"
